static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 20881
    filter_chains:
    - filters:
      - name: envoy.filters.network.dubbo_proxy
        config:
          stat_prefix: dubbo_incomming_stats
          protocol_type: Dubbo
          serialization_type: Hessian2
          route_config:
            name: local_route
            interface: org.apache.dubbo.samples.direct.api.DirectService
            routes:
            - match:
                method:
                  name:
                    exact: sayHello
              route:
                cluster: dubbo_provider
          dubbo_filters:
          - name: envoy.filters.dubbo.router
      
  clusters:
  - name: dubbo_provider
    connect_timeout: 0.250s
    type: static
    lb_policy: round_robin
    load_assignment:
      cluster_name: dubbo_provider
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 20880

