static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 20881
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: dubbo_provider
                http_pre_client_filters:
                - name: envoy.filters.http.dubbo_proxy
                  config:
                    stat_prefix: dubbo_client_stat
                    protocol_type: Dubbo
                    serialization_type: Hessian2
          http_pre_srv_filters:
          - name: envoy.filters.http.dubbo_proxy
            config:
              stat_prefix: dubbo_server_stat 
              protocol_type: Dubbo
              serialization_type: Hessian2
          http_filters:
          - name: envoy.router
            typed_config: {}
  clusters:
  - name: dubbo_provider
    connect_timeout: 0.250s
    type: static
    lb_policy: round_robin
    load_assignment:
      cluster_name: dubbo_provider
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 20880

